import type { Metadata } from 'next';
import { Inter, Karantina } from 'next/font/google';
import './globals.css';

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Carp travel',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>
      <body className={inter.className}>
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
};

export default RootLayout;
