import type { Metadata } from 'next';
import { Inter, Karantina } from 'next/font/google';
import './globals.css';

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '700'],
  subsets: ['latin'],
});

const karantina = Karantina({
  weight: ['400'],
  subsets: ['latin'],
});

// const roboto = Roboto({
//   weight: ['400', '700'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
// });

// Inter Thin 100
// Inter Extra Light 200
// Inter Light 300
// Inter Regular 400
// Inter Medium 500
// Inter Bold 700
// Karantina Regular 400

export const metadata: Metadata = {
  title: 'Carp travel',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />
      </head>
      <body className={inter.className}>
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
};

export default RootLayout;
